# Generated by Django 5.0.2 on 2024-02-11 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docmanagement', '0002_userreport_reportsection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportsection',
            name='modified_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='userapikey',
            name='modified_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='userreport',
            name='modified_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
