# Generated by Django 5.0.2 on 2024-02-11 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docmanagement', '0003_alter_reportsection_modified_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userreport',
            name='ai_generated',
            field=models.BooleanField(default=False),
        ),
    ]
