# Generated by Django 5.0.2 on 2024-02-11 20:25

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('docmanagement', '0004_userreport_ai_generated'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userreport',
            unique_together={('user', 'name', 'revision_number')},
        ),
    ]
