# Generated by Django 5.0.2 on 2024-02-11 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docmanagement', '0005_alter_userreport_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='userreport',
            name='report_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
