from django.urls import path, include
from .views import (
    TestView,
    UploadDocumentView,
    IndexDocumentView,
    ChatPromptView,
    DocumentListView,
    FolderListView,
    RetrieveSecView,
    ReportView,
    NewReportView,
    ReportListView,
    SummarizeView,
    ReportVersionsView,
)

urlpatterns = [
    path("api/test/", TestView.as_view(), name="test"),
    path(
        "api/upload-documents/",
        UploadDocumentView.as_view(),
        name="upload-documents",
    ),
    path(
        "api/index-documents/",
        IndexDocumentView.as_view(),
        name="index-documents",
    ),
    path(
        "api/chat/",
        ChatPromptView.as_view(),
        name="chat",
    ),
    path(
        "api/document-list/",
        DocumentListView.as_view(),
        name="document-list",
    ),
    path(
        "api/folder-list/",
        FolderListView.as_view(),
        name="folder-list",
    ),
    path(
        "api/retrieve-sec/",
        RetrieveSecView.as_view(),
        name="retrieve-sec",
    ),
    path(
        "api/report/",
        ReportView.as_view(),
        name="report",
    ),
    path(
        "api/report-new/",
        NewReportView.as_view(),
        name="report-new",
    ),
    path(
        "api/report-versions/",
        ReportVersionsView.as_view(),
        name="report-versions",
    ),
    path(
        "api/report-list/",
        ReportListView.as_view(),
        name="report-list",
    ),
    path(
        "api/summarize/",
        SummarizeView.as_view(),
        name="summarize",
    ),
]
